sudo: required
services:
    - docker

before_install:
    - docker build -t isitavi/multi-container-test -f ./client/Dockerfile.dev     ./client

scripts:
    - docker run -it isitavi/multi-container-test  npm test -- --coverage

after_sucess:
    - docker build   -t isitavi/multi-client-v1   ./client
    - docker build   -t isitavi/multi-server-v1   ./server
    - docker build   -t isitavi/multi-worker-v1   ./worker
    - docker build   -t isitavi/multi-nginx-v1   ./nginx
    # Docker HUB Credentials
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
    # Push Container to Docker HUB
    - docker push    isitavi/multi-client-v1   
    - docker push    isitavi/multi-server-v1   
    - docker push    isitavi/multi-worker-v1   
    - docker push   isitavi/multi-nginx-v1   